import React,{useEffect,useRef,useState} from 'react';import{createRoot}from'react-dom/client';import{Play,Pause,RotateCw,Activity,HeartPulse,SlidersHorizontal}from'lucide-react';import'./style.css';
const waves=['sine','square','triangle','sawtooth'];
function AudioEngine({playing,wave,freq,master,white,brown}){
 const ctx=useRef(),nodes=useRef([]);
 useEffect(()=>{if(!playing)return; const A=window.AudioContext||window.webkitAudioContext;ctx.current??=new A();let c=ctx.current;
 const osc=c.createOscillator(),g=c.createGain();osc.type=wave;osc.frequency.value=freq;g.gain.value=master/100*.18;osc.connect(g).connect(c.destination);osc.start();
 const mkNoise=(kind,vol)=>{let b=c.createBuffer(1,c.sampleRate*2,c.sampleRate),d=b.getChannelData(0),last=0;for(let i=0;i<d.length;i++){let w=Math.random()*2-1;if(kind==='brown'){last=(last+.02*w)/1.02;d[i]=last*3.5}else d[i]=w}let s=c.createBufferSource(),ng=c.createGain();s.buffer=b;s.loop=true;ng.gain.value=vol/100*.12;s.connect(ng).connect(c.destination);s.start();return[s,ng]};
 nodes.current=[osc,g,...mkNoise('white',white),...mkNoise('brown',brown)];return()=>{nodes.current.forEach(n=>{try{n.stop?.()}catch{}try{n.disconnect?.()}catch{}});nodes.current=[]}},[playing,wave,freq,master,white,brown]);return null}
function App(){const[p,setP]=useState(false),[wave,setW]=useState('sine'),[freq,setF]=useState(432),[master,setM]=useState(70),[white,setWh]=useState(25),[brown,setB]=useState(18);
return <main><AudioEngine playing={p} wave={wave} freq={freq} master={master} white={white} brown={brown}/><header><b>⚛ Vibra<span>Sync</span></b><small>HARMONIA • SAÚDE • CONSCIÊNCIA</small><i>● Protótipo local</i></header>
<div className="layout"><aside>{['⌂ Início','▤ Programas de Tratamento','⌁ Leitura / Bioimpedância','◉ Órgãos e Sistemas','⌁ Frequência Livre','◫ Arquivos','⚙ Configurações'].map((x,i)=><button className={i==3?'on':''}>{x}</button>)}</aside>
<section className="content"><div className="top"><div className="organ card"><h1>Tireoide</h1><p>Sistema Endócrino</p><div className="scene"><div className={'rings '+(p?'spin':'')}><em></em><em></em><em></em></div><div className={'thy '+(p?'pulse':'')}>◖◗</div></div><div className="tools"><button>↻ Girar</button><button>⊕ Aproximar</button><button>◎ Isolar órgão</button></div></div>
<div className="programs card"><h3>Programas relacionados</h3>{['Função da tireoide','Hipotireoidismo','Hipertireoidismo','Tireoidite','Doença de Graves','Bócio','Nódulos tireoidianos','Paratireoide','Equilíbrio hormonal'].map(x=><div>{x}<b>▶</b></div>)}</div>
<div className="reader card"><h3>Leitura / Bioimpedância</h3><Activity size={70}/><p>Módulo reservado para integração posterior com hardware compatível.</p><button>Configurar entrada</button></div></div>
<div className="bottom"><div className="player card"><h3>Player de Frequência</h3><label>Frequência atual <input type="number" value={freq} onChange={e=>setF(+e.target.value)}/> Hz</label><div className="wave">{Array.from({length:18},(_,i)=><i style={{height:(18+Math.abs(Math.sin(i*.8))*48)+'px'}}/> )}</div><button className="play" onClick={()=>setP(!p)}>{p?<Pause/>:<Play/>}</button><strong>{p?'EXECUTANDO':'PRONTO'}</strong></div>
<div className="types card"><h3>Tipo de onda</h3><div>{waves.map(x=><button className={wave==x?'sel':''} onClick={()=>setW(x)}>{x}</button>)}</div><p>Ruídos adicionais são camadas independentes e não alteram a sequência original.</p></div>
<div className="vol card"><h3>Controles de Volume</h3>{[['Frequência original',master,setM],['Ruído branco',white,setWh],['Ruído marrom / castanho',brown,setB]].map(([n,v,s])=><label>{n}<input type="range" value={v} onChange={e=>s(+e.target.value)}/><b>{v}%</b></label>)}</div></div>
</section></div><footer>VibraSync • Protótipo modular • Motor Web Audio + camada anatômica preparada para 3D</footer></main>}createRoot(document.getElementById('root')).render(<App/>);
